[package]
name = "advent2019"
version = "0.1.0"
authors = ["AJ Frantz <aj@ajfrantz.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reformation = "0.5"
itertools = "0.8"
num = "0.2"
